raw_data_path: /media/duyla4/DATA/dataset/PROJECT_DATASET/EKYC/MOVITEL/CARD/PHASE5/raw_data
log_path: /media/duyla4/DATA/dataset/PROJECT_DATASET/EKYC/MOVITEL/CARD/PHASE5/logging/
save_path: /media/duyla4/DATA/dataset/PROJECT_DATASET/EKYC/MOVITEL/CARD/PHASE5/textlines
DIR_PREFIX: '*'
process_only: /media/duyla4/DATA/dataset/PROJECT_DATASET/EKYC/MOVITEL/CARD/PHASE5/logging/error_box.txt
extract_img_only:  

regions:
  CCCD_FRONT_TYPE1:
    - K_
    - LOGO
    - FLAG
    - FIGURE_1
    - FIGURE_2
    - V_SIGN

  CCCD_BACK_TYPE1:
    - K_
    - V_SIGN
    - CHIP
    - UNKNOW
  
  CCCD_BACK_TYPE2:
    - V_SIGN
    - BAR_CODE
    - UNKNOW
    - K_
    
  VOTERCARD_TYPE2:
    - K_
    - V_CEDULA
    - V_SIGN_S
    - HEADER_1
    - HEADER_2
    - HEADER_3
    - UNKNOWN
    - QR_CODE
    - 'QR _CODE'
    - LOGO
    - FIGURE

  BLX_TYPE1:
    - K_
    - UNKNOWN
    - UNKNOW
    - HEADING_EN
    - HEADER_2
    - HEADING_MO
    - HEADER_1
    - V_SIGN
    - FIGURE
    - ENSIGN
  
  BLX_TYPE_2:
    - UNKNOWN
    - HEADING_MO
    - HEADING_EN
    - HEADER
    - ENSIGN
    - K_
    - FIGURE
    - BAR_CODE

  VOTECARD_TYPE1:
    - K_
    - V_SIGN_E
    - V_SIGN_S
    - 'QR _CODE'
    - QR_CODE
    - C_STAMP
    - FIGURE

  CCCD_FRONT_TYPE2:
    - K_
    - FLAG
    - LOGO
    - V_SIGN
    - FIGURE_2
    - FIGURE

  PASSPORT_TYPE_1:
    - K_
    - V_SIGN
    - FIGURE_2
    - HEADING_2
    - HEADER
    - LOGO
    - FIGURE_1
